apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-js
spec:
  selector:
    matchLabels:
      run: vue-js
  replicas: 1
  template:
    metadata:
      labels:
        run: vue-js
    spec:
      containers:
        - name: vue-js
          image: arthurutopios/learn-ci-cd-vue:7a42ca5f-bd3a-58a3-b2d3-cabb5416489f
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: regcred
