apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-js
spec:
  selector:
    matchLabels:
      run: vue-js
  replicas: 1
  template:
    metadata:
      labels:
        run: vue-js
    spec:
      containers:
        - name: vue-js
          image: arthurutopios/learn-ci-cd-vue:9173ab78-b04a-569f-825d-83dcf49d41a3
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: regcred
