apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-js
spec:
  selector:
    matchLabels:
      run: vue-js
  replicas: 1
  template:
    metadata:
      labels:
        run: vue-js
    spec:
      containers:
        - name: vue-js
          image: arthurutopios/learn-ci-cd-vue:2d611d75-3bfe-5dbb-b0c0-6e3a3142b6f8
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: regcred
