apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-js
spec:
  selector:
    matchLabels:
      run: vue-js
  replicas: 1
  template:
    metadata:
      labels:
        run: vue-js
    spec:
      containers:
        - name: vue-js
          image: arthurutopios/learn-ci-cd-vue:604531e7-ae1c-5c2b-b0b9-b593a69c17a9
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: regcred
