name: learn-ci-cd

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set UUID
        id: generate-uuid
        uses: filipstefansson/uuid-action@v1
        with:
          name: ${{ github.sha }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: arthurutopios/learn-ci-cd-vue:${{ steps.generate-uuid.outputs.uuid }}
      - uses: actions/checkout@v4
      - name: Update YAML
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: "deployments/deployment.yaml"
          propertyPath: "spec.template.spec.containers.0.image"
          value: arthurutopios/learn-ci-cd-vue:${{ steps.generate-uuid.outputs.uuid }}
          branch: main
          commitUserName: Arthur
          commitUserEmail: arthur@utopios.solutions
          createPR: 'false'
          message: "Update Image Version to ${{ steps.generate-uuid.outputs.uuid }}"
          token: ${{ secrets.TOKEN }}
