name: learn-ci-cd

on: 
  push:
    branches:
      - main

  pull_request:
    branches:
      -main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v4.0.2
      with:
          node-version: '20'
    - name: npm install
      run: |
        npm install

    - name: npm build
      run: npm build --if-present

    - name: npm test
      id: tests
      run: |
        npm test --passWithNoTests
      env:
        CI: true

    - name: Add heroku remote
      if: ${{success()}}
      run: |
        echo Success
        git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git

    - name: Deploy to heroku
      run: |
        git push heroku HEAD:main -f
        
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: user/app:latest
